---
  ##Create MySQL server(s)
  - hosts: mysql_servers
    become: yes
    roles:
      - role: ansible-role-mysql

  ##Create HAProxy Loadbalancer(s)
  - hosts: load_balancers
    become: yes
    roles:
      - role: ansible-role-haproxy

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- hosts: server_nodes
  become: yes
  roles:
    - role: k3s/master

- hosts: agent_nodes
  become: yes
  roles:
    - role: k3s/node
